
package Project;


public class Historial_Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Historial_Ventas
     */
    BD.Lista_Productos productos = new BD.Lista_Productos();
    
    public Historial_Ventas() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        productos.historial_de_ventas(jTable_Historial);
        productos.Mayor_Stock(jTable_Stock);
        productos.Mas_vendido(jTable_Mas_Vendido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane_Historial = new javax.swing.JScrollPane();
        jTable_Historial = new javax.swing.JTable();
        jLabel_Stock = new javax.swing.JLabel();
        jScrollPane_Stock = new javax.swing.JScrollPane();
        jTable_Stock = new javax.swing.JTable();
        jLabel_Mas = new javax.swing.JLabel();
        jScrollPane_Mas = new javax.swing.JScrollPane();
        jTable_Mas_Vendido = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Historial = new javax.swing.JLabel();
        jButton_Inicio = new javax.swing.JButton();
        jButton_Reg_Prod = new javax.swing.JButton();
        jButton_Vender = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Historial.setViewportView(jTable_Historial);

        getContentPane().add(jScrollPane_Historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 184, 800, 170));

        jLabel_Stock.setText("Producto con mas Stock:");
        getContentPane().add(jLabel_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jTable_Stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Stock.setViewportView(jTable_Stock);

        getContentPane().add(jScrollPane_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 800, 52));

        jLabel_Mas.setText("Producto mas Vendido:");
        getContentPane().add(jLabel_Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jTable_Mas_Vendido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Mas.setViewportView(jTable_Mas_Vendido);

        getContentPane().add(jScrollPane_Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 800, 57));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel_Historial.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_Historial.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Historial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Historial.setText("HISTORIAL DE VENTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Historial, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel_Historial)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        jButton_Inicio.setText("Inicio");
        jButton_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 582, 80, 30));

        jButton_Reg_Prod.setText("Productos");
        jButton_Reg_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Reg_ProdActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Reg_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 582, 100, 30));

        jButton_Vender.setText("Vender");
        jButton_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VenderActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 582, 90, 30));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 582, 90, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 880, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InicioActionPerformed
        // TODO add your handling code here:
        Inicio pasar = new Inicio();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_InicioActionPerformed

    private void jButton_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VenderActionPerformed
        // TODO add your handling code here:
        Venta pasar = new Venta();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_VenderActionPerformed

    private void jButton_Reg_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Reg_ProdActionPerformed
        // TODO add your handling code here:
        Productos_Inv pasar = new Productos_Inv();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Reg_ProdActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButton_Inicio;
    private javax.swing.JButton jButton_Reg_Prod;
    private javax.swing.JButton jButton_Vender;
    private javax.swing.JLabel jLabel_Historial;
    private javax.swing.JLabel jLabel_Mas;
    private javax.swing.JLabel jLabel_Stock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane_Historial;
    private javax.swing.JScrollPane jScrollPane_Mas;
    private javax.swing.JScrollPane jScrollPane_Stock;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable_Historial;
    private javax.swing.JTable jTable_Mas_Vendido;
    private javax.swing.JTable jTable_Stock;
    // End of variables declaration//GEN-END:variables
}
