package Project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Productos_Inv extends javax.swing.JFrame {

    /**
     * Creates new form Productos_Inv
     */
    BD.Categorias categorias = new BD.Categorias();
    BD.Guardar_Registros Registrar = new BD.Guardar_Registros();
    BD.Lista_Productos productos = new BD.Lista_Productos();
    BD.Conexion_DB bd = new BD.Conexion_DB();
    BD.Validar validar = new BD.Validar();

    public Productos_Inv() {
        initComponents();
        
        setLocationRelativeTo(null);

        DefaultComboBoxModel cb_categorias = new DefaultComboBoxModel(categorias.mostrar_Categorias());
        jComboBox_Categoria.setModel(cb_categorias);

        productos.ver_productos_registrados(jTable_Lista_Productos);
        Bloquear();
        jButton_Cancelar.setVisible(false);
        jTextField_ID.setVisible(false);
    }

    void Bloquear() {
        jTextField_Nombre.setEnabled(false);
        jTextField_Cantidad.setEnabled(false);
        jTextField_ID.setEnabled(false);
        jTextField_Peso.setEnabled(false);
        jTextField_Precio.setEnabled(false);
        jTextField_Referencia.setEnabled(false);
        jComboBox_Categoria.setEnabled(false);

        jButton_Guardar.setEnabled(false);
        jButton_Editar.setEnabled(false);
        jButton_Eliminar.setEnabled(false);
    }

    void Desbloquear() {
        jTextField_Nombre.setEnabled(true);
        jTextField_Cantidad.setEnabled(true);
        jTextField_ID.setEnabled(true);
        jTextField_Peso.setEnabled(true);
        jTextField_Precio.setEnabled(true);
        jTextField_Referencia.setEnabled(true);
        jComboBox_Categoria.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel_Referencia = new javax.swing.JLabel();
        jLabel_Precio = new javax.swing.JLabel();
        jTextField_Precio = new javax.swing.JTextField();
        jLabel_Peso = new javax.swing.JLabel();
        jTextField_Peso = new javax.swing.JTextField();
        jLabel_Categoria = new javax.swing.JLabel();
        jComboBox_Categoria = new javax.swing.JComboBox<>();
        jLabel_Cantidad = new javax.swing.JLabel();
        jTextField_Cantidad = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jScrollPane_Lista_Productos = new javax.swing.JScrollPane();
        jTable_Lista_Productos = new javax.swing.JTable();
        jTextField_Referencia = new javax.swing.JTextField();
        jButton_Recargar = new javax.swing.JButton();
        jTextField_ID = new javax.swing.JTextField();
        jButton_Nuevo = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Ventas = new javax.swing.JButton();
        jButton_Inicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Nombre.setText("Nombre:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 130, 60, 30));
        getContentPane().add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, 30));

        jLabel_Referencia.setText("Referencia:");
        getContentPane().add(jLabel_Referencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 80, 40));

        jLabel_Precio.setText("Precio: $");
        getContentPane().add(jLabel_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 50, 30));

        jTextField_Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PrecioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 120, 30));

        jLabel_Peso.setText("Peso:");
        getContentPane().add(jLabel_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 50, 30));

        jTextField_Peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PesoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 90, 30));

        jLabel_Categoria.setText("Categoria:");
        getContentPane().add(jLabel_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 210, 70, 30));

        jComboBox_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        getContentPane().add(jComboBox_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 207, 120, 30));

        jLabel_Cantidad.setText("Cantidad:");
        getContentPane().add(jLabel_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 207, -1, 30));

        jTextField_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CantidadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 207, 110, 30));

        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 80, 30));

        jButton_Editar.setText("Editar");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 262, -1, 30));

        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 30));

        jTable_Lista_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Lista_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Lista_ProductosMouseClicked(evt);
            }
        });
        jScrollPane_Lista_Productos.setViewportView(jTable_Lista_Productos);

        getContentPane().add(jScrollPane_Lista_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 770, 209));
        getContentPane().add(jTextField_Referencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 127, 110, 30));

        jButton_Recargar.setText("Recargar");
        jButton_Recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RecargarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Recargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, 30));
        getContentPane().add(jTextField_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 72, 30));

        jButton_Nuevo.setText("Nuevo");
        jButton_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, 30));

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, 30));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jButton_Ventas.setText("Ventas");
        jButton_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VentasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, 30));

        jButton_Inicio.setText("Inicio");
        jButton_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, 30));

        jLabel2.setText("gr.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 940, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        // TODO add your handling code here:
        Boolean condicion;

        condicion = jTextField_Nombre.getText().equals("") || jTextField_Referencia.getText().equals("") || jTextField_Precio.getText().equals("") || jTextField_Peso.getText().equals("") || jTextField_Cantidad.getText().equals("");
        condicion = condicion || jComboBox_Categoria.getSelectedIndex() == 0;
        if (condicion) {
            JOptionPane.showMessageDialog(null, "Por Favor, llene los campos vacios", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {

            String nombre, referencia, prec, pes, cantidad;
            int precio, peso, stock, categoria;
            BD.Categorias cb_cate = (BD.Categorias) this.jComboBox_Categoria.getSelectedItem();

            nombre = this.jTextField_Nombre.getText();
            referencia = this.jTextField_Referencia.getText();

            categoria = cb_cate.getId_cate();
            prec = this.jTextField_Precio.getText();
            pes = this.jTextField_Peso.getText();
            cantidad = this.jTextField_Cantidad.getText();

            precio = Integer.parseInt(prec);
            peso = Integer.parseInt(pes);
            stock = Integer.parseInt(cantidad);

            LocalDateTime fecha_de_creacion = LocalDateTime.now();

            Registrar.registrar_prod(nombre, referencia, precio, peso, stock, fecha_de_creacion, categoria);
            jTextField_Nombre.setText("");
            jTextField_Referencia.setText("");
            jTextField_Precio.setText("");
            jTextField_Peso.setText("");
            jTextField_Cantidad.setText("");
            jComboBox_Categoria.setSelectedIndex(0);
            jButton_Guardar.setEnabled(false);
            jButton_Cancelar.setVisible(false);
        }

    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jButton_RecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RecargarActionPerformed
        // TODO add your handling code here:
        productos.ver_productos_registrados(jTable_Lista_Productos);
        jTextField_Nombre.setText("");
        jTextField_Referencia.setText("");
        jTextField_Precio.setText("");
        jTextField_Peso.setText("");
        jTextField_Cantidad.setText("");
        jTextField_ID.setText("");
        jComboBox_Categoria.setSelectedIndex(0);
        
        Bloquear();
        jButton_Cancelar.setVisible(false);
    }//GEN-LAST:event_jButton_RecargarActionPerformed

    private void jTable_Lista_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Lista_ProductosMouseClicked
        // TODO add your handling code here:

        jButton_Guardar.setEnabled(false);
        jButton_Editar.setEnabled(true);
        jButton_Eliminar.setEnabled(true);
        jButton_Cancelar.setVisible(true);
        Desbloquear();
        if (evt.getButton() == 1) {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = bd.Conectando();
            try {

                int fila = jTable_Lista_Productos.getSelectedRow();
                String sql = "Select id_prod, nombre_prod, referencia_prod, precio_prod, peso_prod, stock_prod, id_cate from productos Where id_prod=" + jTable_Lista_Productos.getValueAt(fila, 0);
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.next();
                jTextField_ID.setText(rs.getString("id_prod"));
                jTextField_Nombre.setText(rs.getString("nombre_prod"));
                jTextField_Referencia.setText(rs.getString("referencia_prod"));
                jTextField_Precio.setText(rs.getString("precio_prod"));
                jTextField_Peso.setText(rs.getString("peso_prod"));
                jTextField_Cantidad.setText(rs.getString("stock_prod"));
                jTextField_Referencia.setText(rs.getString("referencia_prod"));
                jComboBox_Categoria.setSelectedIndex(rs.getInt("id_cate"));

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jTable_Lista_ProductosMouseClicked

    private void jButton_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NuevoActionPerformed
        // TODO add your handling code here:
        Desbloquear();
        jButton_Guardar.setEnabled(true);
        jButton_Cancelar.setVisible(true);
    }//GEN-LAST:event_jButton_NuevoActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        // TODO add your handling code here:
        Boolean condicion;

        condicion = jTextField_Nombre.getText().equals("") || jTextField_Referencia.getText().equals("") || jTextField_Precio.getText().equals("") || jTextField_Peso.getText().equals("") || jTextField_Cantidad.getText().equals("");
        condicion = condicion || jComboBox_Categoria.getSelectedIndex() == 0;
        if (condicion) {
            JOptionPane.showMessageDialog(null, "Campos vacios", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                bd.ConectarBasedeDatos();

                String nombre, referencia, prec, pes, cantidad, cod;
                int precio, peso, stock, categoria, id;
                BD.Categorias cb_cate = (BD.Categorias) this.jComboBox_Categoria.getSelectedItem();

                nombre = this.jTextField_Nombre.getText();
                referencia = this.jTextField_Referencia.getText();
                prec = this.jTextField_Precio.getText();
                precio = Integer.parseInt(prec);
                pes = this.jTextField_Peso.getText();
                peso = Integer.parseInt(pes);
                categoria = cb_cate.getId_cate();
                cantidad = this.jTextField_Cantidad.getText();
                stock = Integer.parseInt(cantidad);
                LocalDateTime fecha_de_creacion = LocalDateTime.now();
                cod = this.jTextField_ID.getText();
                id = Integer.parseInt(cod);

                bd.sentencia.execute("UPDATE productos	SET nombre_prod='" + nombre + "', referencia_prod='" + referencia + "', precio_prod='" + precio + "', peso_prod='" + peso + "', stock_prod='" + stock + "', fecha_creacion_prod='" + fecha_de_creacion + "', id_cate='" + categoria + "' WHERE  id_prod='" + id + "'");

                JOptionPane.showMessageDialog(null, "El Producto ha sido actualizado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                jTextField_Nombre.setText("");
                jTextField_Referencia.setText("");
                jTextField_Precio.setText("");
                jTextField_Peso.setText("");
                jTextField_Cantidad.setText("");
                jComboBox_Categoria.setSelectedIndex(0);
                jTextField_ID.setText("");

                bd.DesconectarBasedeDatos();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
        jButton_Cancelar.setVisible(false);

    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        Bloquear();
        jTextField_Nombre.setText("");
        jTextField_Referencia.setText("");
        jTextField_Precio.setText("");
        jTextField_Peso.setText("");
        jTextField_Cantidad.setText("");
        jComboBox_Categoria.setSelectedIndex(0);
        jTextField_ID.setText("");
        jButton_Cancelar.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // TODO add your handling code here:
        try {
            bd.ConectarBasedeDatos();
            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = bd.Conectando();
            int fila = jTable_Lista_Productos.getSelectedRow();
            String sql = "DELETE FROM productos	WHERE id_prod=" + jTable_Lista_Productos.getValueAt(fila, 0);
            bd.sentencia.execute(sql);

            JOptionPane.showMessageDialog(null, "Los datos han sido elminados", "Información", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
        
        jButton_Cancelar.setVisible(false);
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InicioActionPerformed
        // TODO add your handling code here:
        Inicio pasar = new Inicio();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_InicioActionPerformed

    private void jButton_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VentasActionPerformed
        // TODO add your handling code here:
        Venta pasar = new Venta();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_VentasActionPerformed

    private void jTextField_PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PrecioKeyTyped
        // TODO add your handling code here:
        validar.Validar_Numeros(evt);
    }//GEN-LAST:event_jTextField_PrecioKeyTyped

    private void jTextField_PesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PesoKeyTyped
        // TODO add your handling code here:
        validar.Validar_Numeros(evt);
    }//GEN-LAST:event_jTextField_PesoKeyTyped

    private void jTextField_CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CantidadKeyTyped
        // TODO add your handling code here:
        validar.Validar_Numeros(evt);
    }//GEN-LAST:event_jTextField_CantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos_Inv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_Inicio;
    private javax.swing.JButton jButton_Nuevo;
    private javax.swing.JButton jButton_Recargar;
    private javax.swing.JButton jButton_Ventas;
    private javax.swing.JComboBox<String> jComboBox_Categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Cantidad;
    private javax.swing.JLabel jLabel_Categoria;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Peso;
    private javax.swing.JLabel jLabel_Precio;
    private javax.swing.JLabel jLabel_Referencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane_Lista_Productos;
    private javax.swing.JTable jTable_Lista_Productos;
    private javax.swing.JTextField jTextField_Cantidad;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Peso;
    private javax.swing.JTextField jTextField_Precio;
    private javax.swing.JTextField jTextField_Referencia;
    // End of variables declaration//GEN-END:variables
}
